### ISSUE TITLE
Create Stories Page

### ISSUE THREAD

**Issue by parkhabit** [dwyl/bestevidence-site#20]
- [x] Create tell us your story section that scrolls to contact form
- [x] Style with 3 cards
- [x] Give cards a set hight and on read more click expand text 
- [x] Include contact form

**Comment by iteles** [comment]
Could not test that the 'Read More/Read less' button actually works as no more content was revealed when 'Read More' was clicked 😊 

http://best-evidence-site.herokuapp.com/stories

**Comment by RobStallion** [comment]
@iteles The 'Read more/Read less' button should be hidden if the text is not over a certain length. I think all the text on this page is currently too short to get it to show up. I'll update it now to allow it to be tested

**Comment by iteles** [comment]
It's the second 'story' that it appears on:
<img width="1038" alt="screen shot 2018-03-29 at 15 16 25" src="https://user-images.githubusercontent.com/4185328/38094987-33d334fe-3367-11e8-976b-6a29a9ed2d97.png">

**Comment by RobStallion** [comment]
Ahh It looks like the issue is with the width of the screen effecting the height of the div the box is in. It looks like on your current screen the text is **just** long enough that it displays the `read more` button but because it only just makes the limit there is nothing extra to display when it is pressed.

This should be a fairly quick fix.

**Comment by iteles** [comment]
🎉 Thanks @RobStallion
